language: scala
scala:
  - 2.12.10
  - 2.13.1
jdk:
  - openjdk8
script:
  - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
notifications:
  webhooks:
    urls:
      - https://nulab-inc.com/hubot/travis?room=3741
    on_success: change
